[package]
name = "pcb"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
description = "next-gen tooling for pcb design"
homepage = { workspace = true }
authors = { workspace = true }

[package.metadata.wix]
upgrade-guid = "8F8B3FF2-0D55-454F-B80D-1E216FCA6C42"
path-guid = "019D9AC1-AFB6-4D44-9FE5-F7BCA676A7DF"
license = false
eula = false

[[bin]]
name = "pcb"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
pcb-zen-core = { workspace = true }
pcb-zen = { workspace = true }
pcb-sch = { workspace = true }
pcb-layout = { workspace = true }
pcb-sim = { workspace = true }
pcb-render = { workspace = true }
log = { workspace = true }
ariadne = { workspace = true }
env_logger = { workspace = true }
colored = { workspace = true }
pcb-kicad = { workspace = true }
open = { workspace = true }
inquire = { workspace = true }
pcb-ui = { workspace = true }
pcb-fmt = { workspace = true }
pathdiff = { workspace = true }
starlark = { workspace = true }
starlark_syntax = { workspace = true }
comfy-table = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }
zip = { workspace = true }
chrono = { workspace = true }
dir-diff = { workspace = true }
tempfile = { workspace = true }
ignore = { workspace = true }
semver = { workspace = true }
crossterm = { workspace = true }
dirs = { workspace = true }

axoupdater = { version = "0.9", features = ["blocking"] }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }
assert_cmd = { workspace = true }
assert_fs = { workspace = true }
duct = { workspace = true }
pcb-test-utils = { workspace = true }
itertools = { workspace = true }
